format_version: v1.0
type: UniqueComponent
attributes: {id: drvWifiWinc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: DRV_WIFI_WINC_PIO_SRC_SELECT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '104'}
  - type: Menu
    attributes: {id: DRV_WIFI_WINC_RTOS_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: DRV_WIFI_WINC_SPI_INST}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: drv_spi_0}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_SPI_INST_IDX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '0'}
  - type: File
    attributes: {id: DRV_WIFI_WINC_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: spi}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi}
- type: ElementPosition
  attributes: {x: '478', y: '489', id: drvWifiWinc}
