format_version: v1.0
type: UniqueComponent
attributes: {id: twihs0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '100000'}
  - type: Comment
    attributes: {id: TWIHS_CLK_EN_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CHDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '186'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CKDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '2'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CLDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '186'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TWIHS0_I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: atecc608_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: ATECC608_DEP_PLIB_I2C}
- type: ElementPosition
  attributes: {x: '810', y: '80', id: twihs0}
