format_version: v1.0
type: UniqueComponent
attributes: {id: uart4}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '81'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '150000000'}
  - type: File
    attributes: {id: UART_HEADER1}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/uart_6418/templates/plib_uart_ring_buffer.h.ftl}
  - type: Comment
    attributes: {id: UART_NVIC_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: 'true'}
  - type: File
    attributes: {id: UART_SOURCE1}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/uart_6418/templates/plib_uart_ring_buffer.c.ftl}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: 'true'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: UART4_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_console_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_console_UART_dependency}
- type: ElementPosition
  attributes: {x: '455', y: '188', id: uart4}
