files:
- generatedChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
  logicalPath: config\pic32mzef_nvm\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
- generatedChecksum: 39FF52903D784BEF79D3640DC1072AFA
  logicalPath: config\pic32mzef_nvm
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39FF52903D784BEF79D3640DC1072AFA
- generatedChecksum: 040A9CBBFFFC5A6A2F88725F2912A5C4
  logicalPath: config\pic32mzef_nvm
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 040A9CBBFFFC5A6A2F88725F2912A5C4
- generatedChecksum: 87A5D947AFE31A9614B6EBCA3E4CDE81
  logicalPath: config\pic32mzef_nvm
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 87A5D947AFE31A9614B6EBCA3E4CDE81
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: ACEAE40DA9387A2B8AB5EF34436D438A
  logicalPath: config\pic32mzef_nvm\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: ACEAE40DA9387A2B8AB5EF34436D438A
- generatedChecksum: 5B6962F1A74E124B9C980F7081E1C736
  logicalPath: config\pic32mzef_nvm\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5B6962F1A74E124B9C980F7081E1C736
- generatedChecksum: 3C7C095EED6124F30CFCDC0A3AFC6808
  logicalPath: config\pic32mzef_nvm\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3C7C095EED6124F30CFCDC0A3AFC6808
- generatedChecksum: 451DBD4978CF3ECC195A212174414B4F
  logicalPath: config\pic32mzef_nvm\peripheral\nvm
  name: plib_nvm.c
  physicalPath: peripheral\nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 451DBD4978CF3ECC195A212174414B4F
- generatedChecksum: A23B32777EF29B2C42E47DFAFC5AE91D
  logicalPath: config\pic32mzef_nvm\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: A23B32777EF29B2C42E47DFAFC5AE91D
- generatedChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
  logicalPath: config\pic32mzef_nvm\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
- generatedChecksum: 684C1B450BD0C0ADF455296291954A10
  logicalPath: config\pic32mzef_nvm\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 684C1B450BD0C0ADF455296291954A10
- generatedChecksum: 3A3D90BBDFDB486B57C8FED3BA7D4135
  logicalPath: config\pic32mzef_nvm\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A3D90BBDFDB486B57C8FED3BA7D4135
- generatedChecksum: B854E2ADC62D967BFAC0C316F31871D7
  logicalPath: config\pic32mzef_nvm
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B854E2ADC62D967BFAC0C316F31871D7
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\pic32mzef_nvm
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mzef_nvm\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: B38028A617FDD4D90B80660771629645
  logicalPath: config\pic32mzef_nvm\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: B38028A617FDD4D90B80660771629645
- generatedChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
  logicalPath: config\pic32mzef_nvm\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
- generatedChecksum: 7C954B20EDAB3F13455008470691E59C
  logicalPath: config\pic32mzef_nvm\peripheral\nvm
  name: plib_nvm.h
  physicalPath: peripheral\nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: 7C954B20EDAB3F13455008470691E59C
- generatedChecksum: 826443BC0DE904951AF65CBAEF9DED7E
  logicalPath: config\pic32mzef_nvm\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 826443BC0DE904951AF65CBAEF9DED7E
- generatedChecksum: 903175300C64256E267D1DB8F91D7861
  logicalPath: config\pic32mzef_nvm\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 903175300C64256E267D1DB8F91D7861
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mzef_nvm\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mzef_nvm\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mzef_nvm
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 9175BBED360A1F5665567266A2A2A4FA
  logicalPath: config\pic32mzef_nvm
  name: p32MZ2048EFM144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 9175BBED360A1F5665567266A2A2A4FA
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzef_nvm;../src/packs/PIC32MZ2048EFM144_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzef_nvm;../src/packs/PIC32MZ2048EFM144_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
