configName: aws_demos
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: aws_cloud;bsp;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;net;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.4.70\atdf\ATSAME54P20A.atdf
