format_version: v1.0
type: UniqueComponent
attributes: {id: cryptoauthlib_pkcs11}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CAL_PKCS11_AWS_FREERTOS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CAL_PKCS11_MAX_SESSIONS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '12'}
- type: ElementPosition
  attributes: {x: '170', y: '180', id: cryptoauthlib_pkcs11}
